### ISSUE TITLE
fs_shapeDNA.py

### ISSUE THREAD

**Issue by junjiaoFeng** [reuter-lab/BrainPrint#2]
Dear Professor Martin Reuter,
         Recently, I have read your paper ‘shapeDNA’ and BrainPrint' ',  and  I would like to do some analysis using our data .so, I downloaded the python scripts (fs_shapeDNA.py ,fs_brainPrint.py) from 'BrianPrint Scripts'  website.
      and   I ran the command : python fs_shapeDNA.py --sdir  **\* --sid \*  --surf  surf/lh.thickness  --outdir  out/.

 however ,it reported errors: 
![error](https://cloud.githubusercontent.com/assets/18643618/14767932/2e084c9e-0a65-11e6-88d3-6a7d6652993b.png)

  I am looking forward to hearing form you !
  Thank you for your kind help!

 Sincerely,

**Comment by m-reuter** [comment]
We just fixed the TypeError, so your error message will look more meaningful. Probably you did not install shapeDNA-tria (download from our Website, see README) and did not set the SHAPEDNA_HOME environment variable to that location?
Also you cannot call it on a thickness file, you need to pass a surface after --surf (e.g. surf/lh.pial ).

**Comment by m-reuter** [comment]
0125e8728af52460bb2993022e4a60a466cb332a fixes TypeError
