### ISSUE TITLE
Unknown reasons to run shapeDNA-tria-osx 

### ISSUE THREAD

**Issue by sparkler0323** [reuter-lab/BrainPrint#5]
Hello,

Sorry for disturbing you, I would like to run shapeDNA-tria-osx in my mac under the instructions, but only to get killed: 9. (Memory is enough)

Did you ever face the same error?

Thank you very much

**Comment by m-reuter** [comment]
Hi, I never get that, but maybe you are running on an unsupported Mac OS version. I did not test it with the most recent ones.
