### ISSUE TITLE
The number of structures

### ISSUE THREAD

**Issue by cyctbdbw** [reuter-lab/BrainPrint#6]
Dear Prof. Reuter,

I have a question regarding the number of structures that are calculated via BrainPrint. In the BrainPrint paper (Wachinger et al., 2015), there are 44 structures calculated, but it seems only 34 structures in the python code. Would you mind guide me on this? Thank you very much and I look forward to hearing from you.

Sincerely yours,
Yu-Chi Chen

**Comment by m-reuter** [comment]
Hi Yu-Chi,

this code has 34 structures + 4 3D volumetric descriptors (lh rh GM WM also as 3D tet-mesh). 
Around lines 309 in fs_brainPrint you can find the definitions of the original BrainPrint (there we have 43 structures). Some structures were merged or removed in the updated version. E.g. choroid plexus is not used as individual structure but combined with the ventricle to produce a well defined structure.
